// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY8XWf6JXQr70CT62D-DKjb53V6Jn0Law',
    appId: '1:818413279566:web:6d6e4969c41e6acbf6661f',
    messagingSenderId: '818413279566',
    projectId: 'agriai-9064a',
    authDomain: 'agriai-9064a.firebaseapp.com',
    storageBucket: 'agriai-9064a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4n_IYRUNifZ2k2xbzXtQL0EEOaJWjpnI',
    appId: '1:818413279566:android:0848f71f2616aea2f6661f',
    messagingSenderId: '818413279566',
    projectId: 'agriai-9064a',
    storageBucket: 'agriai-9064a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2glgFlvRNWZqLbFH6PS_DNWnhK1laXVI',
    appId: '1:818413279566:ios:21af00911a03639ef6661f',
    messagingSenderId: '818413279566',
    projectId: 'agriai-9064a',
    storageBucket: 'agriai-9064a.firebasestorage.app',
    iosBundleId: 'com.example.agriAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2glgFlvRNWZqLbFH6PS_DNWnhK1laXVI',
    appId: '1:818413279566:ios:21af00911a03639ef6661f',
    messagingSenderId: '818413279566',
    projectId: 'agriai-9064a',
    storageBucket: 'agriai-9064a.firebasestorage.app',
    iosBundleId: 'com.example.agriAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY8XWf6JXQr70CT62D-DKjb53V6Jn0Law',
    appId: '1:818413279566:web:06e67c523f26c2bef6661f',
    messagingSenderId: '818413279566',
    projectId: 'agriai-9064a',
    authDomain: 'agriai-9064a.firebaseapp.com',
    storageBucket: 'agriai-9064a.firebasestorage.app',
  );
}
